from typing import Any

class Document:
    name: str
    owner: str
    creation: Any
    modified: Any
    doctype: str
    flags: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def append(self, key: str, value: Any) -> None: ...
    def save(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...
    def reload(self) -> None: ...
    def run_method(self, method: str, *args: Any, **kwargs: Any) -> Any: ...

