from typing import Any

class _DB:
    def get_value(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_value(self, *args: Any, **kwargs: Any) -> Any: ...
    def exists(self, *args: Any, **kwargs: Any) -> Any: ...
    def count(self, *args: Any, **kwargs: Any) -> int: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...
    def sql(self, *args: Any, **kwargs: Any) -> Any: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...

class _Session:
    user: str

class _Utils:
    def __getattr__(self, name: str) -> Any: ...

# Standard Frappe Exceptions
class ValidationError(Exception): ...
class PermissionError(Exception): ...
class DoesNotExistError(Exception): ...
class NameError(Exception): ...
class MandatoryError(Exception): ...
class InvalidStatusError(Exception): ...
class DuplicateEntryError(Exception): ...
class AuthenticationError(Exception): ...
class LinkValidationError(Exception): ...
class OutgoingEmailError(Exception): ...
class SessionStopped(Exception): ...

db: _DB
session: _Session
conf: Any
qb: Any
utils: _Utils
local: Any
request: Any
response: Any
flags: Any

def _(msg: str, *args: Any, **kwargs: Any) -> str: ...
def get_doc(*args: Any, **kwargs: Any) -> Any: ...
def new_doc(*args: Any, **kwargs: Any) -> Any: ...
def get_all(*args: Any, **kwargs: Any) -> Any: ...
def get_list(*args: Any, **kwargs: Any) -> Any: ...
def get_value(*args: Any, **kwargs: Any) -> Any: ...
def get_roles(*args: Any, **kwargs: Any) -> list[str]: ...
def has_permission(*args: Any, **kwargs: Any) -> bool: ...
def whitelist(*args: Any, **kwargs: Any) -> Any: ...
def throw(*args: Any, **kwargs: Any) -> Any: ...
def msgprint(*args: Any, **kwargs: Any) -> Any: ...
def only_for(*args: Any, **kwargs: Any) -> Any: ...
def publish_realtime(*args: Any, **kwargs: Any) -> Any: ...
def format_date(*args: Any, **kwargs: Any) -> str: ...
def format_datetime(*args: Any, **kwargs: Any) -> str: ...
def copy_doc(*args: Any, **kwargs: Any) -> Any: ...
def delete_doc(*args: Any, **kwargs: Any) -> Any: ...
def rename_doc(*args: Any, **kwargs: Any) -> Any: ...
def get_cached_doc(*args: Any, **kwargs: Any) -> Any: ...
def get_cached_value(*args: Any, **kwargs: Any) -> Any: ...
def parse_json(*args: Any, **kwargs: Any) -> Any: ...
def as_json(*args: Any, **kwargs: Any) -> str: ...

def __getattr__(name: str) -> Any: ...

